### ISSUE TITLE
burpsuite 最新版报错

### ISSUE THREAD

**Issue by getcode2git** [API-Security/APIKit#1]
也不能右键doscan

`
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.soap.ApiTypeSoap.urlAddPath(ApiTypeSoap.java:96)
	at burp.application.apitypes.soap.ApiTypeSoap.isFingerprintMatch(ApiTypeSoap.java:62)
	at burp.application.ApiScanner.detect(ApiScanner.java:30)
	at burp.PassiveScanner.doPassiveScan(PassiveScanner.java:45)
	at burp.hs6.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

`
好像扫描会有重复，两个扫出来是一模样的
![image](https://user-images.githubusercontent.com/16176349/143869366-e635bf9f-a89d-4be4-aab7-b9ba1f7e7476.png)

**Comment by maybe-why-not** [comment]
不能右键doscan +1

**Comment by yuligesec** [comment]
/mappings中存在应用所有的路由，并不重复，最新版burp确实存在无法do API scan的情况，后续会考虑解决。

**Comment by agilesecurity** [comment]
> /mappings中存在应用所有的路由，并不重复，最新版burp确实存在无法do API scan的情况，后续会考虑解决。

我用的最新的社区版，它的jre是17，然后我重新编译了代码用jdk17，然后放入extender，还是不工作。
我切换成老的burp版本，它的jre是8，然后用jdk1.8编译，然后放入extender，工作！

**Comment by JianfuYang** [comment]
> 

请问大佬，后面这个问题是怎么解决的呢

**Comment by 2270632741** [comment]
安装1.3版本还是像上面一样报错，请问怎么解决呢，burp2022.12.5的，jdk17

**Comment by yuligesec** [comment]
请用最新版再尝试一下。
