### ISSUE TITLE
加载成功使用时报错，是我环境问题吗

### ISSUE THREAD

**Issue by Y0n3er** [API-Security/APIKit#27]
java.lang.NullPointerException
	at burp.utils.RedirectUtils.isRedirectedResponse(RedirectUtils.java:82)
	at burp.application.apitypes.rest.ApiTypeRest.urlAddPath(ApiTypeRest.java:102)
	at burp.application.apitypes.rest.ApiTypeRest.isFingerprintMatch(ApiTypeRest.java:58)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by yuligesec** [comment]
我这没有这个问题，影响使用吗？请描述清楚你的环境。

**Comment by CKevens** [comment]
what is the version of java being used? @

> 我这没有这个问题，影响使用吗？请描述清楚你的环境。

**Comment by hyggevv** [comment]
请问您最后解决了吗

**Comment by P4x1s** [comment]
> 请问您最后解决了吗

报错的大概率是下错了，下载链接在这里：https://github.com/API-Security/APIKit/releases/download/v1.5.2/APIKit-v1.5.2.jar

**Comment by hyggevv** [comment]
谢谢您，已经解决
