### ISSUE TITLE
Burp插件Errors处报以下错误，同个站点朋友的可以测出来我测不出

### ISSUE THREAD

**Issue by Lay0us** [API-Security/APIKit#37]
我的环境
burp 2023.10.2.1
chrome 119.0.6045.159
朋友的环境
burp 2021.7.1
chrome 119.0.6045.159

使用的都是apikit 1.5.2

报错信息
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	... 3 more
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor$AbandonedRequestCleanupRunnable.run(LogProcessor.java:448)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4586)
	at com.nccgroup.loggerplusplus.logentry.LogEntry.processRequest(LogEntry.java:183)
	at com.nccgroup.loggerplusplus.logentry.LogEntry.process(LogEntry.java:142)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor.processEntry(LogProcessor.java:265)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor.lambda$submitNewEntryProcessingRunnable$0(LogProcessor.java:300)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	... 3 more
java.lang.IllegalArgumentException: Invalid data
	at burp.Zueg.ZY(Unknown Source)
	at burp.Zka0.buildHttpRequest(Unknown Source)
	at burp.Zxli.buildHttpRequest(Unknown Source)
	at burp.Zhe4.buildHttpRequest(Unknown Source)
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:112)
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:256)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:71)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.IllegalArgumentException: Invalid data
	at burp.Zueg.ZY(Unknown Source)
	at burp.Zka0.buildHttpRequest(Unknown Source)
	at burp.Zxli.buildHttpRequest(Unknown Source)
	at burp.Zhe4.buildHttpRequest(Unknown Source)
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:112)
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:256)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:71)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor$AbandonedRequestCleanupRunnable.run(LogProcessor.java:448)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4586)
	at com.nccgroup.loggerplusplus.logentry.LogEntry.processRequest(LogEntry.java:183)
	at com.nccgroup.loggerplusplus.logentry.LogEntry.process(LogEntry.java:142)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor.processEntry(LogProcessor.java:265)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor.lambda$submitNewEntryProcessingRunnable$0(LogProcessor.java:300)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	... 3 more
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor$AbandonedRequestCleanupRunnable.run(LogProcessor.java:448)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4586)
	at com.nccgroup.loggerplusplus.logentry.LogEntry.processRequest(LogEntry.java:183)
	at com.nccgroup.loggerplusplus.logentry.LogEntry.process(LogEntry.java:142)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor.processEntry(LogProcessor.java:265)
	at com.nccgroup.loggerplusplus.logview.processor.LogProcessor.lambda$submitNewEntryProcessingRunnable$0(LogProcessor.java:300)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	... 3 more
java.lang.NullPointerException: Cannot invoke "burp.api.montoya.http.message.responses.HttpResponse.headers()" because "<parameter1>" is null
	at burp.Zueg.ZY(Unknown Source)
	at burp.Zka0.analyzeResponse(Unknown Source)
	at burp.Zxli.analyzeResponse(Unknown Source)
	at burp.Zhe4.analyzeResponse(Unknown Source)
	at burp.utils.RedirectUtils.getFinalHttpRequestResponse(RedirectUtils.java:96)
	at burp.utils.RedirectUtils.getRedirectedResponse(RedirectUtils.java:89)
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:123)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:78)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:128)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:78)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

使用ai查看不懂

你的错误堆栈表明在你的Java程序中发生了一系列异常，特别是与你使用的Burp Suite插件（burpsuite插件）相关的异常。让我们逐步解析这些信息：

IndexOutOfBoundsException: Index: 0:

这个错误表明你的代码试图从一个空列表或集合中访问索引0的元素。检查堆栈跟踪中提到的行附近的代码，特别是在LogEntry类及其processRequest方法中。
IllegalArgumentException: Invalid data:

这个错误表明传递给某个方法的一些数据是无效的。在这种情况下，它发生在ApiTypeSwagger类中。检查ApiTypeSwagger类中的urlAddPath和isFingerprintMatch方法，查找潜在问题。
NullPointerException: Cannot invoke "burp.api.montoya.http.message.responses.HttpResponse.headers()" because "<parameter1>" is null:

这个错误是由于空指针异常。堆栈跟踪表明你正在尝试在一个空对象上调用方法。检查ApiTypeSwagger类中的代码，特别是analyzeResponse方法。
NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null:

另一个空指针异常，这次出现在ApiTypeSwagger类中。检查urlAddPath方法和isFingerprintMatch方法附近的代码。
为了排除问题并修复这些错误：

回顾类中的方法（LogEntry、ApiTypeSwagger等），识别可能在没有适当检查null或空条件的情况下访问列表、数组或对象的地方。

确保处理数据可能不符合预期格式或可能缺失的边缘情况。

仔细检查对列表进行基于索引访问的逻辑，以防止IndexOutOfBoundsException。

验证在调用对象上的方法之前，这些对象是否已经初始化，以避免NullPointerException。

可能还有助于查看Burp Suite API文档或你使用的特定插件的文档，以了解可能影响你的代码的任何更改或更新。

如果你能提供更具体的代码片段或有关你的代码相关部分的详细信息，我可以提供更有针对性的帮助。

<img width="1055" alt="image" src="https://github.com/API-Security/APIKit/assets/99304369/577e9776-1a4d-4a9b-b1c7-1667d87812d9">

**Comment by yuligesec** [comment]
根据报错来看是没有获取到response，是不是网络原因没访问网站成功。

**Comment by Lay0us** [comment]
> 根据报错来看是没有获取到response，是不是网络原因没访问网站成功。

可能是插件先后顺序问题，我看数据包里面是log4j插件跑完之后再把流量转到apikit，这种是可以禁用别的插件还是可以设置apikit优先级
