### ISSUE TITLE
安装HaE插件后安装APIKit报错

### ISSUE THREAD

**Issue by hello-noob** [API-Security/APIKit#39]
我的环境
burp 2023.9.2 
APIKit 1.5.3
HaE 2.5.8
两个插件一个安装完再安全另外一个，APIKit 报错，顺序调反去装也是APIKit 报错。
能帮忙看看是什么问题吗？谢谢。
报错信息如下：
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at burp.core.processor.MessageProcessor.processRequestMessage(MessageProcessor.java:41)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:229)
	at burp.Zvdj.isEnabledFor(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zs6r.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy25.isEnabledFor(Unknown Source)
	at burp.Zk2a.ZC(Unknown Source)
	at burp.Zq1x.Zv(Unknown Source)
	at burp.Zgsq.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at burp.Zkz.ZQ(Unknown Source)
	at burp.Zkz.Zt(Unknown Source)
	at burp.Zgsq.Zw(Unknown Source)
	at burp.Zgsq.ZC(Unknown Source)
	at burp.Zibm.Zc(Unknown Source)
	at burp.Zibm.lambda$new$0(Unknown Source)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.addNotify(Component.java:7097)
	at java.desktop/java.awt.Container.addNotify(Container.java:2793)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at burp.Zibm.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:756)
	at burp.Zp47.Zx(Unknown Source)
	at burp.Zp47.Zi(Unknown Source)
	at burp.Zb6j.Zd(Unknown Source)
	at burp.Zb6j.Z_(Unknown Source)
	at burp.Zvdd.ZW(Unknown Source)
	at burp.Zg3l.Zv(Unknown Source)
	at burp.Zsm0.ZY(Unknown Source)
	at burp.Zsm0.lambda$extensionConfigChanged$4(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at burp.core.processor.MessageProcessor.processRequestMessage(MessageProcessor.java:41)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:229)
	at burp.Zvdj.isEnabledFor(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zs6r.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy25.isEnabledFor(Unknown Source)
	at burp.Zk2a.ZC(Unknown Source)
	at burp.Zq1x.Zv(Unknown Source)
	at burp.Zgsq.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at burp.Zkz.ZQ(Unknown Source)
	at burp.Zkz.Zt(Unknown Source)
	at burp.Zgsq.Zw(Unknown Source)
	at burp.Zgsq.ZC(Unknown Source)
	at burp.Zibm.Zc(Unknown Source)
	at burp.Zibm.lambda$new$0(Unknown Source)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.addNotify(Component.java:7097)
	at java.desktop/java.awt.Container.addNotify(Container.java:2793)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at burp.Zibm.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:756)
	at burp.Zp47.Zx(Unknown Source)
	at burp.Zp47.Zi(Unknown Source)
	at burp.Zb6j.Zd(Unknown Source)
	at burp.Zb6j.Z_(Unknown Source)
	at burp.Zvdd.ZW(Unknown Source)
	at burp.Zg3l.Zv(Unknown Source)
	at burp.Zsm0.ZY(Unknown Source)
	at burp.Zsm0.lambda$extensionConfigChanged$4(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
![image](https://github.com/API-Security/APIKit/assets/115137482/5f552964-a5cb-49b8-b4b6-d0644c4f860e)
![Snipaste_2023-11-24_14-28-07](https://github.com/API-Security/APIKit/assets/115137482/1c3ed0a5-5ade-4260-8ac8-42dade740961)

**Comment by yuligesec** [comment]
@gh0stkey

**Comment by yuligesec** [comment]
我和key都没有复现这个问题，请排查一下是不是别的插件导致的。

**Comment by hello-noob** [comment]
已经跟key在沟通了，不是别的插件导致， 就是两个插件一块就出现问题

**Comment by gh0stkey** [comment]
与楼主沟通，最新版应该已经修复这个问题，但没找到问题的原因，等后续新版本发布吧。

**Comment by yuligesec** [comment]
https://github.com/gh0stkey/HaE/releases/tag/2.5.9 
---------------------------------------------------
HaE 2.5.9 更新内容：

BUG修复
  修复Databoard下拉框长时间使用消失问题。
  修复消息报文数据高亮、标注信息不完整问题。
  修复Databoard双击数据对应展示消息报文缺失问题。
  修复正则规则错误导致规则失效问题，并在插件输出中提供报错信息。
  修复空报文数据匹配错误问题，避免与其他插件（如：APIKit）冲突。
UI更新
  修改HaE展示Logo逻辑，使界面不再突兀。

**Comment by hello-noob** [comment]
已测试不再冲突，问题可关闭，感谢两位大佬。 @gh0stkey @yuligesec
