### ISSUE TITLE
加载插件后，使用报错

### ISSUE THREAD

**Issue by Zxc123456zxc** [API-Security/APIKit#41]
burp版本 2023.10  java 17

	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalArgumentException: expected '>' at position 45
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
	at burp.action.ExtractContent.lambda$null$0(ExtractContent.java:76)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yuligesec** [comment]
APIKit里都没有这个 dk.brics.automaton.RegExp 库...是不是和其他插件冲突了。会影响使用吗。。看报错感觉和APIKit没关系呀

**Comment by Zxc123456zxc** [comment]
好使了，我使用低版本burp加载插件，再用高版本打开能用，不影响使用

**Comment by yuligesec** [comment]
好的。
