### ISSUE TITLE
burpsuite v2023.9 安装不了该插件

### ISSUE THREAD

**Issue by zipscan** [API-Security/APIKit#42]
java.lang.Exception: Extension class is not a recognized type
	at burp.Zig1.ZE(Unknown Source)
	at burp.Zig1.Zx(Unknown Source)
	at burp.Zvex.ZN(Unknown Source)
	at burp.Zsm0.Zr(Unknown Source)
	at burp.Zih1.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yuligesec** [comment]
按理应该没问题啊...要不重启下试试
