### ISSUE TITLE
Burpsuite 2023.9安装后无法AutoScan

### ISSUE THREAD

**Issue by Potatowo233** [API-Security/APIKit#50]
java.lang.NullPointerException: Cannot read the array length because the return value of "burp.IHttpRequestResponse.getResponse()" is null
	at burp.utils.RedirectUtils.isRedirectedResponse(RedirectUtils.java:82)
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:122)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:71)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot read the array length because the return value of "burp.IHttpRequestResponse.getResponse()" is null
	at burp.utils.RedirectUtils.isRedirectedResponse(RedirectUtils.java:82)
	at burp.application.apitypes.soap.ApiTypeSoap.urlAddPath(ApiTypeSoap.java:104)
	at burp.application.apitypes.soap.ApiTypeSoap.isFingerprintMatch(ApiTypeSoap.java:70)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot read the array length because the return value of "burp.IHttpRequestResponse.getResponse()" is null
	at burp.utils.RedirectUtils.isRedirectedResponse(RedirectUtils.java:82)
	at burp.application.apitypes.rest.ApiTypeRest.urlAddPath(ApiTypeRest.java:99)
	at burp.application.apitypes.rest.ApiTypeRest.isFingerprintMatch(ApiTypeRest.java:55)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yuligesec** [comment]
必须要有返回包response的页面才可以autoscan
