### ISSUE TITLE
最新版插件仍然报错

### ISSUE THREAD

**Issue by PolarPeak** [API-Security/APIKit#55]
面板没数据
![image](https://github.com/API-Security/APIKit/assets/44831329/9fa48bc7-7334-4ab6-bcc7-4c732f534076)

日志
![image](https://github.com/API-Security/APIKit/assets/44831329/b81e4d8b-6576-4d3c-b9ba-2dfc2635bedc)
![image](https://github.com/API-Security/APIKit/assets/44831329/b9c4dc01-f42c-4386-b95f-a64a95a61fe2)

```
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.soap.ApiTypeSoap.urlAddPath(ApiTypeSoap.java:105)
	at burp.application.apitypes.soap.ApiTypeSoap.isFingerprintMatch(ApiTypeSoap.java:67)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.rest.ApiTypeRest.urlAddPath(ApiTypeRest.java:104)
	at burp.application.apitypes.rest.ApiTypeRest.isFingerprintMatch(ApiTypeRest.java:55)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:132)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:71)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:132)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:74)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.rest.ApiTypeRest.urlAddPath(ApiTypeRest.java:104)
	at burp.application.apitypes.rest.ApiTypeRest.isFingerprintMatch(ApiTypeRest.java:59)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.soap.ApiTypeSoap.urlAddPath(ApiTypeSoap.java:105)
	at burp.application.apitypes.soap.ApiTypeSoap.isFingerprintMatch(ApiTypeSoap.java:69)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "java.net.URL.getPort()" because "url" is null
	at burp.CookieManager.urlToOrigin(CookieManager.java:54)
	at burp.CookieManager.processHttpMessage(CookieManager.java:106)
	at burp.fbl.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.rest.ApiTypeRest.urlAddPath(ApiTypeRest.java:104)
	at burp.application.apitypes.rest.ApiTypeRest.isFingerprintMatch(ApiTypeRest.java:59)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.swagger.ApiTypeSwagger.urlAddPath(ApiTypeSwagger.java:132)
	at burp.application.apitypes.swagger.ApiTypeSwagger.isFingerprintMatch(ApiTypeSwagger.java:74)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getResponse()" because "newHttpRequestResponse" is null
	at burp.application.apitypes.soap.ApiTypeSoap.urlAddPath(ApiTypeSoap.java:105)
	at burp.application.apitypes.soap.ApiTypeSoap.isFingerprintMatch(ApiTypeSoap.java:69)
	at burp.application.ApiScanner$1.run(ApiScanner.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)


```

**Comment by yuligesec** [comment]
这个报错是因为拿不到返回包，是点autoscan触发？注意点autoscan的时候要有返回包

**Comment by fbanjin** [comment]
俺也一样，主面板没东西，报错如下
![image](https://github.com/API-Security/APIKit/assets/165235989/068e6b32-b65a-4503-9f67-f5c59633b01c)
输出
![image](https://github.com/API-Security/APIKit/assets/165235989/ba28acc9-9a94-43d5-b719-f9ea09b0e4c8)

**Comment by fbanjin** [comment]
主面板没东西

output:
```
Scanning	https://g.alicdn.com:443/sd/baxia/2.5.11/
Scanning	https://img.alicdn.com:443/tfs/
Scanning	https://webmail.lopevi.yuntrial.com:443/api/
Scanning	https://g.alicdn.com:443/AWSC/et/1.77.4/
存在敏感数据泄漏，类型为：OSSKey泄漏，匹配到关键字：ACCESSKEY
正在对 https://log.mmstat.com 进行已识别的目录扫描
Scanning	https://static.gdapi.cn:443/retcode/
```

error 输出
```
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "objects[2]" is null
	at burp.core.processor.DataProcessingUnit.lambda$matchContentByRegex$2(DataProcessingUnit.java:71)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by yuligesec** [comment]
> 主面板没东西
> 
> output:
> 
> ```
> Scanning	https://g.alicdn.com:443/sd/baxia/2.5.11/
> Scanning	https://img.alicdn.com:443/tfs/
> Scanning	https://webmail.lopevi.yuntrial.com:443/api/
> Scanning	https://g.alicdn.com:443/AWSC/et/1.77.4/
> 存在敏感数据泄漏，类型为：OSSKey泄漏，匹配到关键字：ACCESSKEY
> 正在对 https://log.mmstat.com 进行已识别的目录扫描
> Scanning	https://static.gdapi.cn:443/retcode/
> ```
> 
> error 输出
> 
> ```
> Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "objects[2]" is null
> 	at burp.core.processor.DataProcessingUnit.lambda$matchContentByRegex$2(DataProcessingUnit.java:71)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
> 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
> ```

没有扫到API文档就不会显示结果
