### ISSUE TITLE
Burpsuit 2023版本使用v1.5.4，被动扫描默认开启，打开后再关闭依旧会扫描所有经过bp的网站

### ISSUE THREAD

**Issue by joonk685** [API-Security/APIKit#65]
Burpsuit 2023版本使用v1.5.4，被动扫描默认开启，打开后再关闭依旧会扫描所有经过bp的网站

**Comment by joonk685** [comment]
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at burp.core.processor.DataProcessingUnit.matchContentByRegex(DataProcessingUnit.java:62)
	at burp.core.processor.MessageProcessor.processResponseMessage(MessageProcessor.java:106)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:26)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:95)
	at burp.Zrco.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zw_1.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zruw.Zd(Unknown Source)
	at burp.Zyp3.Zd(Unknown Source)
	at burp.Zsdb.Zd(Unknown Source)
	at burp.Zqno.Zy(Unknown Source)
	at burp.Zq_y.ZF(Unknown Source)
	at burp.Zq__.Zv(Unknown Source)
	at burp.Zq_1.ZY(Unknown Source)
	at burp.Zq_y.ZY(Unknown Source)
	at burp.Zun5.ZX(Unknown Source)
	at burp.Zrt0.Zu(Unknown Source)
	at burp.Zrt0.ZL(Unknown Source)
	at burp.Zrt0.ZQ(Unknown Source)
	at burp.Zsf5.ZQ(Unknown Source)
	at burp.Zsr_.ZQ(Unknown Source)
	at burp.Zq7s.ZQ(Unknown Source)
	at burp.Zse1.Z_(Unknown Source)
	at burp.Zyc2.Zf(Unknown Source)
	at burp.Zycm.Zf(Unknown Source)
	at burp.Zsb.Zc(Unknown Source)
	at burp.Zuls.Zs(Unknown Source)
	at burp.Zql_.Zm(Unknown Source)
	at burp.Zql_.ZM(Unknown Source)
	at burp.Zriz.ZD(Unknown Source)
	at burp.Zriz.Z_(Unknown Source)
	at burp.Zy_t.Zh(Unknown Source)
	at burp.Zwgb.ZB(Unknown Source)
	at burp.Zwgb.ZU(Unknown Source)
	at burp.Zwgb.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
jregex.PatternSyntaxException: hexadecimal digit expected: u
	at jregex.CharacterClass.toHexDigit(CharacterClass.java:769)
	at jregex.CharacterClass.parseClass(CharacterClass.java:463)
	at jregex.CharacterClass.parseClass(CharacterClass.java:351)
	at jregex.Term.parseTerm(Term.java:1007)
	at jregex.Term.append(Term.java:501)
	at jregex.Term.makeTree(Term.java:259)
	at jregex.Term.makeTree(Term.java:308)
	at jregex.Term.makeTree(Term.java:219)
	at jregex.Term.makeTree(Term.java:206)
	at jregex.Pattern.compile(Pattern.java:164)
	at jregex.Pattern.<init>(Pattern.java:150)
	at jregex.Pattern.<init>(Pattern.java:108)
	at burp.core.processor.DataProcessingUnit.createPatternMatcher(DataProcessingUnit.java:259)
	at burp.core.processor.DataProcessingUnit.matchByRegex(DataProcessingUnit.java:177)
	at burp.core.processor.DataProcessingUnit.lambda$matchContentByRegex$2(DataProcessingUnit.java:103)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223)
	at java.base/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at burp.core.processor.DataProcessingUnit.matchContentByRegex(DataProcessingUnit.java:62)
	at burp.core.processor.MessageProcessor.processResponseMessage(MessageProcessor.java:106)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:26)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:95)
	at burp.Zrco.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zw_1.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zruw.Zd(Unknown Source)
	at burp.Zyp3.Zd(Unknown Source)
	at burp.Zsdb.Zd(Unknown Source)
	at burp.Zqno.Zy(Unknown Source)
	at burp.Zq_y.ZF(Unknown Source)
	at burp.Zq__.Zv(Unknown Source)
	at burp.Zq_1.ZY(Unknown Source)
	at burp.Zq_y.ZY(Unknown Source)
	at burp.Zun5.ZX(Unknown Source)
	at burp.Zrt0.Zu(Unknown Source)
	at burp.Zrt0.ZL(Unknown Source)
	at burp.Zrt0.ZQ(Unknown Source)
	at burp.Zsf5.ZQ(Unknown Source)
	at burp.Zsr_.ZQ(Unknown Source)
	at burp.Zq7s.ZQ(Unknown Source)
	at burp.Zse1.Z_(Unknown Source)
	at burp.Zyc2.Zf(Unknown Source)
	at burp.Zycm.Zf(Unknown Source)
	at burp.Zsb.Zc(Unknown Source)
	at burp.Zuls.Zs(Unknown Source)
	at burp.Zql_.Zm(Unknown Source)
	at burp.Zql_.ZM(Unknown Source)
	at burp.Zriz.ZD(Unknown Source)
	at burp.Zriz.Z_(Unknown Source)
	at burp.Zy_t.Zh(Unknown Source)
	at burp.Zwgb.ZB(Unknown Source)
	at burp.Zwgb.ZU(Unknown Source)
	at burp.Zwgb.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
jregex.PatternSyntaxException: unknown named class: {}
	at jregex.CharacterClass.parseClass(CharacterClass.java:586)
	at jregex.CharacterClass.parseClass(CharacterClass.java:351)
	at jregex.Term.parseTerm(Term.java:1007)
	at jregex.Term.append(Term.java:501)
	at jregex.Term.makeTree(Term.java:259)
	at jregex.Term.makeTree(Term.java:308)
	at jregex.Term.makeTree(Term.java:219)
	at jregex.Term.makeTree(Term.java:206)
	at jregex.Pattern.compile(Pattern.java:164)
	at jregex.Pattern.<init>(Pattern.java:150)
	at burp.core.processor.DataProcessingUnit.createPatternMatcher(DataProcessingUnit.java:259)
	at burp.core.processor.DataProcessingUnit.matchByRegex(DataProcessingUnit.java:177)
	at burp.core.processor.DataProcessingUnit.lambda$matchContentByRegex$2(DataProcessingUnit.java:103)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
jregex.PatternSyntaxException: hexadecimal digit expected: u
	at jregex.CharacterClass.toHexDigit(CharacterClass.java:769)
	at jregex.CharacterClass.parseClass(CharacterClass.java:463)
	at jregex.CharacterClass.parseClass(CharacterClass.java:351)
	at jregex.Term.parseTerm(Term.java:1007)
	at jregex.Term.append(Term.java:501)
	at jregex.Term.makeTree(Term.java:259)
	at jregex.Term.makeTree(Term.java:308)
	at jregex.Term.makeTree(Term.java:219)
	at jregex.Term.makeTree(Term.java:206)
	at jregex.Pattern.compile(Pattern.java:164)
	at jregex.Pattern.<init>(Pattern.java:150)
	at jregex.Pattern.<init>(Pattern.java:108)
	at burp.core.processor.DataProcessingUnit.createPatternMatcher(DataProcessingUnit.java:259)
	at burp.core.processor.DataProcessingUnit.matchByRegex(DataProcessingUnit.java:177)
	at burp.core.processor.DataProcessingUnit.lambda$matchContentByRegex$2(DataProcessingUnit.java:103)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
